version: "3.8"

services:
  mailserver:
    image: docker.io/mailserver/docker-mailserver:latest
    hostname: mail
    domainname: niksusername.com
    env_file:
      - mailserver.env
    ports:
      - target: 25
        published: 25
        protocol: tcp
        mode: host
      - target: 465
        published: 465
        protocol: tcp
        mode: host
      - target: 587
        published: 587
        protocol: tcp
        mode: host
      - target: 143
        published: 143
        protocol: tcp
        mode: host
      - target: 993
        published: 993
        protocol: tcp
        mode: host
    volumes:
      - maildata:/var/mail
      - mailstate:/var/mail-state
      - maillogs:/var/log/mail
      - mailconfig:/tmp/docker-mailserver
      - traefik_acme:/etc/letsencrypt
      - /etc/localtime:/etc/localtime:ro
    cap_add:
      - NET_ADMIN
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.role == manager

volumes:
  maildata:
  mailstate:
  maillogs:
  mailconfig:
  traefik_acme:
    external: true
